on: [ push ]

jobs:
    job:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   id: changes
                uses: ./

            -   run: |
                    echo "Changes: ${{ steps.changes.outputs.text }}"
